//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: letters-we-never-sent (cli)
//! AC description: `letter accept <filename> [--root <dir>]` rewrites the file's frontmatter to set state=accepted and accepted_at=now(RFC3339). The body content is preserved byte-for-byte after the frontmatter. Exit 0 on success.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac3() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC3 not yet implemented — see file header");
}
